# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12N0O9dNyyckRp9Fb3sYY05G_0MW0-v6q
"""

class Sinifi:
  a=5
  b="string"

  def yazdir(self):
    print(self.a)
    print(self.b)

sinif_1=Sinifi

sinif_1.yazdir(sinif_1)

class Araba:
    marka = ""
    model = None

    def __init__(self, marka, model):
        self.marka = marka  # Initialize the marka attribute
        self.model = model

    def get_marka(self):
        return self.marka

    def get_model(self):
        return self.model

araba2 = Araba("porshe", 2003)

araba2.get_marka()

## kalıtım
class Personel:
    maas= 2000
    departman = ""
    isim= ""

    def __init__(self, ad, departman,maas):
        self.isim = ad  # Initialize the marka attribute
        self.departman = departman
        self.maas=maas

##Polymorpishm

class Hayvan:
 isim=""
 ses= ""

 def __init__(self,isim,ses):
    self.isim=isim
    self.ses=ses


 def seslen(self):
      print(f"{self.isim},{self.ses}  sesi çıkarıyorr" )

class Kedi(Hayvan):
  def __init__(self, isim, ses):
     super().__init__(isim, "mırrrrr")

## modüller

import math
math.cos(5)

# try except else finally == try catch aynı

try:
  a=5
  b=0
  print(a/b)
except ZeroDivisionError :
  print("sıfıra bölme hatası")