# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c5zWObPXb9u7NtyJTzozizRgqzilRLV-
"""

print("HEllo world")

2**10

2**10

print(2**10) #üsssülerde böyle kullanılr

a= int(input("birinci değeri gir"))  #değer almak için input kullanılır
b= int(input("ikinici değeri gir"))

a+b

if 1<2:          #if else girdi sistemi ile yapılır.
  print("bir ikiden küçüktür");
if 6>10:
  print("5")

a= [1,2,3,4,5]

a[2]
a[2:5]  #aynı matlabtaki gibi 0 1 2 3 4 gibi gidiyor 2 den 5 e kadar deniyor
a[2:]  # boş koyuybca da hepsi demek oluyor

liste = ["elma","armut","muz"]

liste.append("karpuz ") #liste sonuna ekleme yaptı

liste.count("elma") #sayamaya yarar.

for i in range(15):   #in kullanarak for kullandık
    print("kadir")
    print(i)

# a= 0
# for a<15:
#   a=a+1;
#   print("kadir")  #böyle bir kullanım yok

a = 0
while a < 15:          # bu şekilde kullanılabilir
    a = a + 1
    print("kadir")

for i in range(15):   #Veya bu şekilde range ve in kullanarak yapılır
    print("kadir")
    print(i)

liste = [i for i in range(400)]   #listenin içinde for kullanabiliriz
liste

liste = [i for i in range(400)]
liste

# fonksiyonlar def ile tanımlanır
def karesinial():
  print(5*5)

def karesinial():
  print(5*5)
karesinial()

def karesinial(deger):
  print(deger*deger)
karesinial(6)

def toplam (a,b):
 print (a+b)

toplam(5,9)

